### ISSUE TITLE
Mermaid diagrams are not showing up in output PDF

### ISSUE THREAD

**Issue by adulbrich** [Linkerin/starlight-to-pdf#10]
Hello,

I was initially hidding [Mermaid](https://mermaid.js.org/) diagrams and dispaying a message when printing the webpage, but now that I want to print them, while it works in the browser, it does not work with `starlight-to-pdf`. The border of the diagram shows up in the output pdf but not the diagram itself.

Here's the command I'm using:

```sh
npx starlight-to-pdf \
            "https://cs362.alexulbrich.com/lectures/git-and-github" \
            --format "Letter" \
            --last "/lectures/testing-fundamentals" \
            --exclude "/lectures/testing-fundamentals" \
            --filename "lecture-notes-git-and-github" \
            --no-contents \
            --margins '2cm 1cm 2cm 1cm' \
            --print-bg
```

I've tried with the new scroll delay but there's no latency so it does not change anything.

Any ideas why the diagrams might not be showing up?

Thank you for making my workflow easier with your utility! 👍

**Comment by Linkerin** [comment]
Hello Alex,

Thanks for reaching out! I'm having a bit of trouble understanding the issue you're encountering. I ran the following command to parse your website, and the resulting PDF seems to include everything. Please see the attached file and let me know if I’m missing something.

```bash
npx starlight-to-pdf https://cs362.alexulbrich.com/ --last "lectures/git-and-github" --filename cs362 --no-contents --margins '2cm 1cm 2cm 1cm' --format Letter --print-bg
```

[cs362.pdf](https://github.com/user-attachments/files/19601255/cs362.pdf)

**Comment by adulbrich** [comment]
Hi Alexei,

Thank you for your quick answer!

In your PDF output, for example, you have:

![Image](https://github.com/user-attachments/assets/74f06ee8-c846-45b0-912c-fe8e2fef0f44)

While on the website:

![Image](https://github.com/user-attachments/assets/9afceab8-caae-484e-a0cf-cbd02b38d1c6)

The source block is hidden when printing, but the diagram should not be. When I print from the browser:

![Image](https://github.com/user-attachments/assets/dd692a4c-6b37-487c-8b70-e4f11ba0b8e8)

Hope this makes sense.

**Comment by Linkerin** [comment]
I’ve released version 1.4.0, which includes the new [`--page-wait-until`](https://github.com/Linkerin/starlight-to-pdf?tab=readme-ov-file#-cli-flags-reference-) flag. Setting it to `'networkidle0'` or `'networkidle2'` should help resolve your issue.

**Comment by adulbrich** [comment]
Heya! Thanks for looking into this. I did try it but diagrams are still not showing up. I did try to simulate network activity to trigger the `networkidle0/2` but to no avail yet. I'll try a few other things. The Mermaid diagrams are generated once the DOM is loaded (JS --> SVG) which indeed explains why Puppeteer does not pick it up by default.

**Comment by adulbrich** [comment]
Alright, I got it somewhat working -- I added an `await mermaid.run()` and used `--page-wait-until 'networkidle0'` and now it works most of the time. I still have a few diagrams that fail for some reason (large ones). I'll investigate. Thanks!!

Edit: False alert; it does not work consistently. I ran it a second time and diagrams disappeared again.

**Comment by Linkerin** [comment]
Yeah, the reason was that content loaded event was not enough for the mermaid svgs to be created. That's why the option to fix the issue was to wait a bit longer before scraping the html content of the page.
Before releasing v1.4.0, I tested this solution ~10 times against your website. It was stable. Even now I generated a PDF of your whole website, and from the first glance it looks like everything is fine. Maybe you should try a different environment? 

[cs362.pdf](https://github.com/user-attachments/files/19638122/cs362.pdf)

**Comment by adulbrich** [comment]
In the section on Test Driven Development in your genearted PDF, the ROT13 Cypher diagram (a pretty large block diagram) is not rendered still --

I did try a custom run of Puppeteer where I wait for `class="mermaid"` and `svg` to be present (in addition to the `networkidle0`) and that works better, but you have no guarantee that the user will nothave used a custom class name for their mermaid diagram...
